# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_broker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message_broker.proto\"0\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\")\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2c\n\rMessageBroker\x12$\n\x07Publish\x12\x0f.PublishRequest\x1a\x06.Empty\"\x00\x12,\n\tSubscribe\x12\x11.SubscribeRequest\x1a\x08.Message\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST']._serialized_start=24
  _globals['_PUBLISHREQUEST']._serialized_end=72
  _globals['_SUBSCRIBEREQUEST']._serialized_start=74
  _globals['_SUBSCRIBEREQUEST']._serialized_end=107
  _globals['_MESSAGE']._serialized_start=109
  _globals['_MESSAGE']._serialized_end=150
  _globals['_EMPTY']._serialized_start=152
  _globals['_EMPTY']._serialized_end=159
  _globals['_MESSAGEBROKER']._serialized_start=161
  _globals['_MESSAGEBROKER']._serialized_end=260
# @@protoc_insertion_point(module_scope)
